tasks:
  unified_intelligence:
    desc: "Unified Intelligence Platform"
    dir: unified_intelligence
    silent: true
    aliases: [ui, rag, agent, iagent]
    cmds:
      - watchexec -w . -e py -- uv run main.py

  devops:
    desc: "DevSecOps | GitOps | CICD | Kubernetes"
    dir: devops
    silent: true
    aliases: [pipeline, gitops, cicd, deployment]
    cmds:
      - watchexec -w . -e py -- uv run main.py

  abs:
    desc: "Adaptive Bitrate Playback & Streaming Platform"
    dir: adaptive_bitrate_streaming
    silent: true
    aliases: ["adaptive-bitrate-streaming"]
    cmds:
      - watchexec -w . -e py -- uv run main.py
